export const domElements = {
  loginContainer: document.querySelector('.login-container'),
  emailLoginInput: document.querySelector('#email-login'),
  passwordLoginInput: document.querySelector('#password-login'),
  loginForm: document.querySelector('.login-form'),
  wrongAlert: document.querySelector('.wrong-email-password-text'),
  container: document.querySelector('.container'),
  navigation: document.querySelector('.nav'),
  overlay: document.querySelector('.overlay'),
  //
  dashboardBtn: document.querySelector('.dashboard-btn'),
  booksBtn: document.querySelector('.books-btn'),
  membersBtn: document.querySelector('.members-btn'),
  //
  main: document.querySelector('.main'),
  //
  dashboard: document.querySelector('.dashboard'),
  membersNumber: document.querySelector('.members_number'),
  booksNumber: document.querySelector('.books_number'),
  dashboardSeeAllBooks: document.querySelector('.dashboard-see-all-books'),
  dashboardSeeAllMembers: document.querySelector('.dashboard-see-all-members'),
  //
  books: document.querySelector('.books'),
  addNewBookBtn: document.querySelector('.add-new-book_btn'),
  booksList: document.querySelector('.books-list'),
  bookID: document.querySelector('.book-id-p'),
  bookTitle: document.querySelector('.book-title-p'),
  bookAuthor: document.querySelector('.book-author-p'),
  bookStatus: document.querySelector('.book-status-p'),
  editBookBtn: document.querySelector('.edit-book'),
  deleteBookBtn: document.querySelector('.delete-book'),
  //
  members: document.querySelector('.members'),
  addNewMemberBtn: document.querySelector('.add-new-member_btn'),
  membersList: document.querySelector('.members-list'),
  membershipNo: document.querySelector('.membership-no-p'),
  memberName: document.querySelector('.name-p'),
  phone: document.querySelector('.phone-p'),
  email: document.querySelector('.email-p'),
  memberFine: document.querySelector('.fine-p'),
  editMemberBtn: document.querySelector('.edit-member'),
  deleteMemberBtn: document.querySelector('.delete-member'),
  //add book
  addBookBox: document.querySelector('.add-book-box'),
  addBookForm: document.querySelector('.add-book-form'),
  inputAddBookId: document.querySelector('.add-book-id'),
  inputAddBookTitle: document.querySelector('.add-book-title'),
  inputAddBookAuthor: document.querySelector('.add-book-author'),
  radioInput: document.querySelector('.radio-input'),
  formAddBookBtn: document.querySelector('.add-book-btn'),
  formBookCancel: document.querySelector('.cancel-book-btn'),
  formEditBook: document.querySelector('.edit-book-form'),
  cancelEditBook: document.querySelector('.cancel-edit-book-btn'),
  updateBookBtn: document.querySelector('.edit-book-btn'),
  //add member
  addMemberBox: document.querySelector('.add-member-box'),
  addMemberForm: document.querySelector('.add-member-form'),
  inputMembershipNo: document.querySelector('.membership-no-input'),
  inputMembersName: document.querySelector('.members-name-input'),
  inputMembersPhone: document.querySelector('.members-phone-input'),
  inputMembersEmail: document.querySelector('.members-email-input'),
  inputMembersFineDue: document.querySelector('.members-fine_due-input'),
  formAddMemberBtn: document.querySelector('.add-member-btn'),
  formMemberCancel: document.querySelector('.cancel-member-btn'),
};
